### ISSUE TITLE
使用后没有效果

### ISSUE THREAD

**Issue by lordleonli** [misonomika525/tenhou-se-and-bg#1]
URL使用后声音并没有变化，不知道哪里存在问题。

**Comment by lordleonli** [comment]
https://raw.githubusercontent.com/TanakaKotoha/tenhou-se-and-bg/master/SEA.json
请问是不是我使用URL格式错误呢？

**Comment by lordleonli** [comment]
已找到原因，挂代理解决。

**Comment by MorinoSakura** [comment]
githubusercontent.com 国内是没法直连的，挂代理在所难免。

另外，如果要自己调整角色的话，中间的TanakaKotoha请换成自己的GitHub用户名，
如：用户名是lordleonli，则要把URL改成——https://raw.githubusercontent.com/lordleonli/tenhou-se-and-bg/master/SEA.json
其他同理。

**Comment by DongZiyu506** [comment]
哦终于知道怎么解决了
